### ISSUE TITLE
CSS Minification

### ISSUE THREAD

**Issue by chadaort** [humanmade/webpack-helpers#2]
Need a way to add plugins to postcss like cssnano or another way to minify css.

**Comment by goldenapples** [comment]
In looking into this, my initial inclination was to leave this one out of webpack-helpers and let it be handled on the project level.

In order to use a CSS minimizer along with mini-css-extract-plugin, we'd have to specify it in the `optimization` section of the config file... along with specifying a JS optimization tool. (see https://github.com/webpack-contrib/mini-css-extract-plugin#minimizing-for-production for example code.)

But... given that minifying CSS for production is a common need (and we already have an `optimization` configuration defined in the production presets) it might be good to bundle `optimize-css-assets-webpack-plugin` with this repo and add it to the default optimization strategy.

**Comment by kadamwhite** [comment]
@chadaort @goldenapples I've released v0.4.0 which includes the generator added in #3. Thanks for opening the issue!
